# Generated by Django 4.2.7 on 2025-05-12 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('users', '0002_user_branch_user_current_rank_user_primary_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_commissioning', to='onboarding.commissionstage'),
        ),
    ]
