# Generated by Django 4.2.7 on 2025-05-12 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_name', models.CharField(max_length=200)),
                ('situation', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('execution', models.TextField(blank=True, null=True)),
                ('service_support', models.TextField(blank=True, null=True)),
                ('command_signal', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('classification', models.CharField(choices=[('Unclassified', 'Unclassified'), ('Confidential', 'Confidential'), ('Secret', 'Secret'), ('Top Secret', 'Top Secret')], default='Unclassified', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_opords', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_opords', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
