# Generated by Django 4.2.7 on 2025-05-12 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '__first__'),
        ('operations', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('Operation', 'Operation'), ('Training', 'Training'), ('Ceremony', 'Ceremony'), ('Meeting', 'Meeting'), ('Social', 'Social'), ('Other', 'Other')], default='Training', max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('coordinates', models.CharField(blank=True, help_text='For in-game locations', max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('max_participants', models.IntegerField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('required_units', models.JSONField(blank=True, null=True)),
                ('required_ranks', models.JSONField(blank=True, null=True)),
                ('briefing_url', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Postponed', 'Postponed')], default='Scheduled', max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('host_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_events', to='units.unit')),
                ('operation_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_linked', to='operations.operationorder')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Attending', 'Attending'), ('Declined', 'Declined'), ('Maybe', 'Maybe'), ('Excused', 'Excused'), ('No Response', 'No Response')], default='No Response', max_length=20)),
                ('response_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('performance_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
