# Generated by Django 4.2.7 on 2025-05-12 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('badge_image_url', models.URLField(blank=True, null=True)),
                ('is_required_for_promotion', models.BooleanField(default=False)),
                ('expiration_period', models.IntegerField(blank=True, help_text='Days until expiration, null for no expiration', null=True)),
                ('authorized_trainers', models.JSONField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='units.branch')),
                ('min_rank_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_for_certificates', to='units.rank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('certificate_file_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revocation_reason', models.TextField(blank=True, null=True)),
                ('revocation_date', models.DateTimeField(blank=True, null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingcertificate')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_certificates', to=settings.AUTH_USER_MODEL)),
                ('training_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'certificate', 'is_active')},
            },
        ),
    ]
