# Generated by Django 4.2.7 on 2025-06-08 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0003_unithierarchyview_unithierarchynode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('Tank', 'Tank'), ('APC', 'Armored Personnel Carrier'), ('IFV', 'Infantry Fighting Vehicle'), ('Artillery', 'Artillery'), ('Helicopter', 'Helicopter'), ('Transport', 'Transport'), ('Support', 'Support'), ('Other', 'Other')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Maintenance', 'Maintenance'), ('Damaged', 'Damaged'), ('Destroyed', 'Destroyed'), ('Reserve', 'Reserve')], default='Operational', max_length=20)),
                ('crew_size', models.IntegerField(default=1)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='units.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
