# Generated by Django 4.2.7 on 2025-06-08 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('units', '0002_alter_userposition_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitHierarchyView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('view_type', models.CharField(choices=[('full', 'Full Organization'), ('branch', 'Branch Specific'), ('custom', 'Custom View'), ('operational', 'Operational Structure'), ('administrative', 'Administrative Structure')], default='full')),
                ('layout_config', models.JSONField(blank=True, default=dict)),
                ('node_positions', models.JSONField(blank=True, default=dict)),
                ('node_styles', models.JSONField(blank=True, default=dict)),
                ('filter_config', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('show_vacant_positions', models.BooleanField(default=True)),
                ('show_personnel_count', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hierarchy_views', to=settings.AUTH_USER_MODEL)),
                ('included_units', models.ManyToManyField(blank=True, related_name='hierarchy_views', to='units.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitHierarchyNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('custom_style', models.JSONField(blank=True, default=dict)),
                ('show_details', models.BooleanField(default=True)),
                ('expanded', models.BooleanField(default=True)),
                ('hierarchy_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='units.unithierarchyview')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
            options={
                'unique_together': {('hierarchy_view', 'unit')},
            },
        ),
    ]
